"""Locate and load the pre-simulated datasets the notebooks use.

Every notebook obtains its files through :func:`load_dataset`, which resolves a dataset id
(the ids in ``docs/outline.md``'s dependency table and ``pipelines/config/datasets.yaml``) to a
directory on disk. Resolution order:

1. ``$DWIBOOK_DATA/<id>`` if the environment variable is set and the directory exists. This is
   how the book is built against fresh pipeline output before a data release exists.
2. The pooch cache, populated from the GitHub release pinned by :data:`DATA_TAG` and the
   checksums in ``registry.txt``.

The registry is generated by ``pipelines/scripts/package_release.py``; it is never edited by
hand. Appendix B (the data manifest) is rendered from the same file.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

import nibabel as nib
import numpy as np

#: Tag of the GitHub release that holds the datasets. Bumped by the release script.
DATA_TAG = "data-v0.0"
_REPO = "PennLINC/diffusion-book"
_REGISTRY_FILE = Path(__file__).with_name("registry.txt")


def _registry() -> dict[str, str]:
    """Parse ``registry.txt`` (pooch format: ``<path> <sha256>`` per line)."""
    entries: dict[str, str] = {}
    if not _REGISTRY_FILE.exists():
        return entries
    for line in _REGISTRY_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        path, digest = line.split()
        entries[path] = digest
    return entries


def registered_datasets() -> list[str]:
    """Dataset ids present in the registry (the first path component of each entry)."""
    return sorted({p.split("/", 1)[0] for p in _registry()})


@dataclass(frozen=True)
class Dataset:
    """A resolved dataset directory with small conveniences for BIDS-style contents."""

    id: str
    path: Path

    def file(self, name: str) -> Path:
        """Path to a file inside the dataset; raises if it is missing."""
        p = self.path / name
        if not p.exists():
            raise FileNotFoundError(f"{name} not found in dataset {self.id!r} at {self.path}")
        return p

    def nifti(self, name: str) -> nib.Nifti1Image:
        return nib.load(self.file(name))

    def volume(self, name: str, dtype=np.float32) -> np.ndarray:
        return np.asarray(self.nifti(name).dataobj, dtype=dtype)

    def bvals_bvecs(self, stem: str) -> tuple[np.ndarray, np.ndarray]:
        """Load ``<stem>.bval`` / ``<stem>.bvec`` (FSL layout) as ``(n,)`` and ``(n, 3)`` arrays."""
        bvals = np.loadtxt(self.file(f"{stem}.bval"))
        bvecs = np.loadtxt(self.file(f"{stem}.bvec")).T
        return bvals, bvecs

    def files(self) -> list[Path]:
        return sorted(p for p in self.path.rglob("*") if p.is_file())


def _local_override(dataset_id: str) -> Path | None:
    root = os.environ.get("DWIBOOK_DATA")
    if not root:
        return None
    candidate = Path(root) / dataset_id
    return candidate if candidate.is_dir() else None


def load_dataset(dataset_id: str) -> Dataset:
    """Resolve a dataset id to a local directory, fetching from the data release if needed."""
    local = _local_override(dataset_id)
    if local is not None:
        return Dataset(dataset_id, local)

    registry = _registry()
    members = [p for p in registry if p.split("/", 1)[0] == dataset_id]
    if not members:
        known = ", ".join(registered_datasets()) or "none yet"
        raise KeyError(
            f"dataset {dataset_id!r} is not in the registry (known: {known}) and "
            f"$DWIBOOK_DATA/{dataset_id} does not exist. Run the pipeline in pipelines/ and set "
            f"DWIBOOK_DATA, or wait for a data release that includes it."
        )

    import pooch  # imported lazily so the package works without network access

    fetcher = pooch.create(
        path=pooch.os_cache("dwibook"),
        base_url=f"https://github.com/{_REPO}/releases/download/{DATA_TAG}/",
        registry={p: registry[p] for p in members},
    )
    for member in members:
        fetcher.fetch(member)
    return Dataset(dataset_id, Path(fetcher.abspath) / dataset_id)
